import RegisteredDevices from "../../../model/mobileadmin_registereddevices"

export const ColumnOverride: { [key: string]: string } = {
    serialNumber: 'Serial Number',
    ownerTeam: 'Device Owner',
    registerDate: 'Register Date',
    gsWave: 'gsWave',
    assignedUser: 'Assigned User',
    checkUser: 'Check-in User',
    checkTimestamp: 'Check-in Time',
    ashift: 'A-Shift User',
    bshift: 'B-Shift User',
    cshift: 'C-Shift User',
    dshift: 'D-Shift User',
    deviceNotes: 'Device Notes',
    ModelId: 'Model ID',
    ModelName: 'Model Name',
    AndroidVer: 'Android Version',
    MacAddress: 'MAC Address',
    IMEI: 'IMEI',
    ICCId: 'ICCId',
    PhoneNum: 'Phone Number',
    McuvicId: 'mCUVIC ID',
    EMMId: 'EMM ID',
    EMMGroup: 'EMM Group',
    VPNId: 'VPN ID',
    LastUserGhrId: 'Last User GHR',
    mysingle_id: 'Last User Single',
    nt_id: 'Last User NTID',
    full_name: 'Last User Name',
    dept_name_short: 'Department',
    LastUserDeptName: 'Department Full',
    LastUserTimestamp: 'Last Activity',
    LastAPTimestamp: 'Last AP Timestamp',
    LastAp: 'Last AP Location'
}

export const RenderColumns: Array<keyof RegisteredDevices>  = [
    'serialNumber',
    'assignedUser',
    'full_name',
    'ownerTeam',
    //'registerDate',
    'gsWave',
    //'checkUser',
    //'checkTimestamp',
    //'ashift',
    //'bshift',
    //'cshift',
    //'dshift',
    'deviceNotes',
    //'ModelId',
    //'ModelName',
    //'AndroidVer',
    //'MacAddress',
    //'IMEI',
    //'ICCId',
    //'PhoneNum',
    //'McuvicId',
    //'EMMId',
    //'EMMGroup',
    //'VPNId',
    //'LastUserGhrId', // Last User GHR Number
    //'mysingle_id', // Last User Single ID
    //'nt_id', // Last User NTID
    //'dept_name_short',
    //'LastUserDeptName',
    'LastUserTimestamp',
    //'LastAPTimestamp',
    'LastAp'
]